module(..., package.seeall)
local 派发器 = require("公用.派发器")
local 协议ID = require("公用.协议ID")
local 计时器ID = require("公用.计时器ID")
local 事件处理 = require("技能.事件处理")

--派发器.RegisterTimerHandler(计时器ID.TIMER_ATTACK_OUT, 事件处理.OnAttackOut)
派发器.RegisterTimerHandler(计时器ID.TIMER_ATTACK_HIT, 事件处理.OnAttackHit)
派发器.RegisterTimerHandler(计时器ID.TIMER_BUFF_HIT, 事件处理.OnBuffHit)
派发器.RegisterTimerHandler(计时器ID.TIMER_BUFF_END, 事件处理.OnBuffEnd)
--派发器.RegisterTimerHandler(计时器ID.TIMER_ATTACK_HITFLY, 事件处理.OnAttackHitfly)
--派发器.RegisterTimerHandler(计时器ID.TIMER_ATTACK_DISPLACE, 事件处理.OnAttackDisplace)
派发器.RegisterTimerHandler(计时器ID.TIMER_DISPLACE_BEGIN, 事件处理.OnDisplaceBegin)
派发器.RegisterTimerHandler(计时器ID.TIMER_DISPLACE_END, 事件处理.OnDisplaceEnd)
派发器.RegisterTimerHandler(计时器ID.TIMER_CHANGE_BODYID, 事件处理.OnChangeBodyID)

派发器.RegisterTimerHandler(计时器ID.TIMER_UNATTACKABLE_OUT, 事件处理.OnUnattackableOut)
派发器.RegisterTimerHandler(计时器ID.TIMER_UNMOVABLE_OUT, 事件处理.OnUnmovableOut)
派发器.RegisterTimerHandler(计时器ID.TIMER_MONSTER_DISAPPEAR, 事件处理.OnMonsterDisappear)
